Added project languages to built_w_pass.md
SecurityLab-UCD/OSS-Fuzz-scripts pull request #22
Opened 2023-05-30 19:37 UTC by ethanbwang

2023-05-30 21:31 UTC, EYH0602 requested changes

2023-05-30 21:31 UTC, EYH0602 commented on built_w_pass.md
> +6. alembic,c++ (auto_build_w_pass c++)
please use the same line-format for autobuilds and the others so the parsing is easier

like
```md
5. [lua](./oss-fuzz/projects/lua/build_w_pass.sh),c
6. alembic(auto_build_w_pass c++),c++ 
```

2023-05-31 03:45 UTC, DataCorrupted approved these changes

2023-05-31 22:16 UTC, EYH0602 approved these changes

2023-05-31 22:17 UTC, merged