Documentation Changes
SecurityLab-UCD/OSS-Fuzz-scripts pull request #46
Opened 2023-09-28 22:14 UTC by ethanbwang

I finished this a while ago forgot to push and create a PR.

2023-09-28 22:30 UTC, EYH0602 requested changes

2023-09-28 22:30 UTC, EYH0602 commented on built_w_pass.md
> +7. [libpng](https://github.com/SecurityLab-UCD/oss-fuzz/blob/8d65054c1e3b09409521d80ce1b382a096905a40/projects/libpng/build_w_pass.sh),c++
Since those `build_w_pass.sh`s are already merged into the master, we should use `.../blob/master/projects/...` in the URL instead of the commit id.

2023-09-28 22:30 UTC, EYH0602 commented on built_w_pass.md
> +# Projects that can be build with [ReportPass](https://github.com/SecurityLab-UCD/ReportFunctionExecutedPass/tree/60ed2c299a060c36afd644ba86d9613d9cca7c7b)
`https://github.com/SecurityLab-UCD/ReportFunctionExecutedPass/` is fine

2023-09-28 22:52 UTC, ethanbwang commented
Sorry ignore the above I'll put it in a separate PR after this one gets merged.

2023-09-29 20:28 UTC, EYH0602 approved these changes

2023-09-30 06:00 UTC, merged